### ISSUE TITLE
Remove Old Lessons From Short Week Layouts | React Swap

### ISSUE THREAD

**Issue by vstankatz** [epicodus-curriculum/react-full-stack#3]
_This Issue is a duplicate made from the old epicodus-classroom page._ This issue will address the same issues talked about [here](https://github.com/epicodus-classroom/c-sharp-curriculum/issues/320) but currently some of the short week layout files refer to the old curriculum for NoSQL and APIs with React. These should be changed to the new lessons for each to create uniformity across FT & PT and to make sure any React Swap related lessons are correctly updated. Currently all C# lessons refer to the update lessons and no active YAML file refers to [old lessons](https://github.com/epicodus-classroom/c-sharp-curriculum/tree/main/0_old). _For sake of time only the new lessons are being revised with the React Swap"_

- [x] [PT Week 36 Short Week WITH UPDATE TO 35](https://github.com/epicodus-classroom/part-time-curriculum/blob/main/pt_full_stack/3_react_pt_full_stack/wk36_short_WITH_UPDATE_TO_35_react_pt_full_stack.yaml) and [PT Week 35 Short Week](https://github.com/epicodus-classroom/part-time-curriculum/blob/main/pt_full_stack/3_react_pt_full_stack/wk36_short_react_pt_full_stack.yaml) should be updated to use `3_new_react_with...` instead of old. Currently there is **new** a short week outline for this week but it was not used in the most recent cohort, the UPDATE TO 35 version was, so PT teachers will need to decide which outline they would like to use. For now an easy fix is to update both.
- [x] [PT Week 37 Short Week](https://github.com/epicodus-classroom/part-time-curriculum/blob/main/pt_full_stack/3_react_pt_full_stack/wk37_short_react_pt_full_stack.yaml) should be updated to use `4_new_apis...` instead of old.

**Comment by erik-t-irgens** [comment]
> [PT Week 36 Short Week WITH UPDATE TO 35](https://github.com/epicodus-classroom/part-time-curriculum/blob/main/pt_full_stack/3_react_pt_full_stack/wk36_short_WITH_UPDATE_TO_35_react_pt_full_stack.yaml) and [PT Week 35 Short Week](https://github.com/epicodus-classroom/part-time-curriculum/blob/main/pt_full_stack/3_react_pt_full_stack/wk36_short_react_pt_full_stack.yaml) should be updated to use 3_new_react_with... instead of old. Currently there is new a short week outline for this week but it was not used in the most recent cohort, the UPDATE TO 35 version was, so PT teachers will need to decide which outline they would like to use. For now an easy fix is to update both.

It looks like the version that has been imported to LHTP 2.0 is the second example, which is quite different. The version that is in LHTP 2.0 is what was/is currently active on LHTP 1.0, leaving out all other files. For now, I've gone ahead and updated that file to be a full week. I'll continue to evaluate the order of lessons for React as we move more stuff, and might reevaluate the layout :) 

> [PT Week 37 Short Week](https://github.com/epicodus-classroom/part-time-curriculum/blob/main/pt_full_stack/3_react_pt_full_stack/wk37_short_react_pt_full_stack.yaml) should be updated to use 4_new_apis... instead of old.

For this, it actually looks like all files in the original classroom repo were short weeks. There are many differences between these files because there have been changes in focus around hooks, react-router, and other technology. The most recently updated file (As of July) is the one that is currently active. Looking at the commit history, there's this: 

> [short week july4th](https://github.com/epicodus-classroom/part-time-curriculum/commit/7c3597f7d3d6a2bf77679a0865f66e291404a0a5) 
Removed tuesday. Had the same lesson as Monday
@[mtb116](https://github.com/epicodus-classroom/part-time-curriculum/commits?author=mtb116)
mtb116 committed on Jun 27

So I'll just reinstate that lesson for the missing day. Cheers for this!
